<script setup lang="ts">
import { useApiClient } from '~/services/api-client'
import type { AuditLogEntry } from '~/types/audit'
import type { LedgerEntry } from '~/types/ledger'
definePageMeta({ layout: 'admin' })
const logs = ref<AuditLogEntry[]>([]); const ledger = ref<LedgerEntry[]>([]); const action = ref(''); const targetType = ref(''); const loading = ref(true); const error = ref<string | null>(null); const success = ref<string | null>(null)
async function load(): Promise<void> { loading.value = true; error.value = null; try { const api = useApiClient(); const query: Record<string, string> = {}; if (action.value) query.action = action.value; if (targetType.value) query.targetType = targetType.value; const result = await Promise.all([api.request<AuditLogEntry[]>('/admin/audit-logs', Object.keys(query).length ? { query } : {}), api.request<LedgerEntry[]>('/admin/ledger')]); logs.value = result[0]; ledger.value = result[1]; success.value = 'Audit and ledger records refreshed.' } catch (caught: unknown) { logs.value = []; ledger.value = []; error.value = caught instanceof Error ? caught.message : 'Audit records could not be loaded.' } finally { loading.value = false } }
onMounted(load)
</script>
<template><main class="mx-auto max-w-6xl px-6 py-10"><h1 class="text-3xl font-bold">Ledger & audit trail</h1><div class="mt-5 flex gap-3"><input v-model="action" class="rounded border px-3 py-2" placeholder="Filter action"><input v-model="targetType" class="rounded border px-3 py-2" placeholder="Filter target type"><button class="rounded border px-4" @click="load">Apply filters</button></div><p v-if="error" class="mt-4 rounded bg-red-50 p-3 text-red-700">{{ error }}</p><p v-if="success" class="mt-4 rounded bg-emerald-50 p-3 text-emerald-700">{{ success }}</p><div v-if="loading" class="mt-6 h-32 animate-pulse rounded bg-slate-100" /><template v-else><p v-if="!logs.length && !ledger.length" class="mt-6 rounded border border-dashed p-8 text-center">No immutable audit or ledger records match these filters.</p><section class="mt-6 overflow-x-auto rounded border"><h2 class="p-4 font-bold">Audit logs (read-only)</h2><table class="w-full text-left text-sm"><tbody><tr v-for="log in logs" :key="log.id" class="border-t"><td class="p-3">{{ new Date(log.createdAt).toLocaleString() }}</td><td>{{ log.actorId }}</td><td>{{ log.action }}</td><td>{{ log.targetType }}: {{ log.targetId }}</td></tr></tbody></table></section><section class="mt-6 overflow-x-auto rounded border"><h2 class="p-4 font-bold">Financial ledger (append-only)</h2><table class="w-full text-left text-sm"><tbody><tr v-for="entry in ledger" :key="entry.id" class="border-t"><td class="p-3">{{ entry.type }}</td><td>{{ entry.amountMinor }} {{ entry.currency }}</td><td>{{ entry.paymentId }}</td></tr></tbody></table></section></template></main></template>
