<script setup lang="ts">
import { useApiClient } from '~/services/api-client'
import type { AuditLogEntry } from '~/types/audit'
import type { PaginatedResult } from '~/types/api'
import type { LedgerEntry } from '~/types/ledger'
definePageMeta({ layout: 'admin' })
const logs=ref<AuditLogEntry[]>([]);const ledger=ref<LedgerEntry[]>([]);const action=ref('');const targetType=ref('');const loading=ref(true);const error=ref<string|null>(null);const logMeta=ref({total:0,page:1,pageSize:10});const ledgerMeta=ref({total:0,page:1,pageSize:10})
async function loadLogs(page=logMeta.value.page){loading.value=true;try{const result=await useApiClient().request<PaginatedResult<AuditLogEntry>>('/admin/audit-logs',{query:{page,pageSize:logMeta.value.pageSize,...(action.value?{action:action.value}:{}),...(targetType.value?{targetType:targetType.value}:{})}});logs.value=result.items;logMeta.value=result.meta}catch(e:unknown){error.value=e instanceof Error?e.message:'Audit records could not be loaded.'}finally{loading.value=false}}
async function loadLedger(page=ledgerMeta.value.page){try{const result=await useApiClient().request<PaginatedResult<LedgerEntry>>('/admin/ledger',{query:{page,pageSize:ledgerMeta.value.pageSize}});ledger.value=result.items;ledgerMeta.value=result.meta}catch(e:unknown){error.value=e instanceof Error?e.message:'Ledger could not be loaded.'}}
async function refresh(){await Promise.all([loadLogs(1),loadLedger(1)])} onMounted(refresh)
</script>
<template><main class="page-wrap"><h1 class="text-3xl font-black">Ledger & audit trail</h1><div class="mt-5 flex flex-wrap gap-3"><input v-model="action" class="field max-w-xs" placeholder="Filter action"><input v-model="targetType" class="field max-w-xs" placeholder="Filter target type"><button class="btn-secondary" @click="refresh">Apply filters</button></div><p v-if="error" class="mt-4 rounded-xl bg-red-50 p-3 text-red-700">{{error}}</p><div v-if="loading" class="mt-6 h-32 animate-pulse rounded-2xl bg-slate-200"/><template v-else><section class="table-shell mt-6"><h2 class="border-b p-4 font-bold">Audit logs</h2><table class="w-full text-left text-sm"><tbody><tr v-for="log in logs" :key="log.id" class="border-t"><td class="p-3">{{new Date(log.createdAt).toLocaleString()}}</td><td>{{log.actorName}}</td><td>{{log.action}}</td><td>{{log.targetName}}</td></tr></tbody></table><UiPagination :page="logMeta.page" :total="logMeta.total" :page-size="logMeta.pageSize" @update:page="loadLogs"/></section><section class="table-shell mt-6"><h2 class="border-b p-4 font-bold">Financial ledger</h2><table class="w-full text-left text-sm"><tbody><tr v-for="entry in ledger" :key="entry.id" class="border-t"><td class="p-3 capitalize">{{entry.type.replaceAll('_',' ')}}</td><td>{{formatUzs(entry.amountMinor)}}</td><td>{{entry.paymentName}}</td><td>{{entry.memberName}}</td></tr></tbody></table><UiPagination :page="ledgerMeta.page" :total="ledgerMeta.total" :page-size="ledgerMeta.pageSize" @update:page="loadLedger"/></section></template></main></template>
