<script setup lang="ts">
import { useApiClient } from '~/services/api-client'
import type { AuditLogEntry } from '~/types/audit'
import type { LedgerEntry } from '~/types/ledger'
definePageMeta({ layout: 'admin' })
const logs = ref<AuditLogEntry[]>([]); const ledger = ref<LedgerEntry[]>([]); const action = ref(''); const targetType = ref(''); const loading = ref(true); const error = ref<string | null>(null)
async function load(): Promise<void> { loading.value = true; error.value = null; try { const query: Record<string,string> = {}; if(action.value) query.action=action.value; if(targetType.value) query.targetType=targetType.value; const api=useApiClient(); [logs.value, ledger.value] = await Promise.all([api.request<AuditLogEntry[]>('/admin/audit-logs', Object.keys(query).length ? {query}:{}), api.request<LedgerEntry[]>('/admin/ledger')]) } catch(caught:unknown) { error.value=caught instanceof Error?caught.message:'Audit records could not be loaded.' } finally { loading.value=false } }
onMounted(load)
</script>
<template><main class="page-wrap"><h1 class="text-3xl font-black">Ledger & audit trail</h1><div class="mt-5 flex flex-wrap gap-3"><input v-model="action" class="field max-w-xs" placeholder="Filter action"><input v-model="targetType" class="field max-w-xs" placeholder="Filter target type"><button class="btn-secondary" @click="load">Apply filters</button></div><p v-if="error" class="mt-4 rounded-xl bg-red-50 p-3 text-red-700">{{ error }}</p><div v-if="loading" class="mt-6 h-32 animate-pulse rounded-2xl bg-slate-200"/><template v-else><section class="table-shell mt-6"><h2 class="border-b p-4 font-bold">Audit logs</h2><table class="w-full text-left text-sm"><tbody><tr v-for="log in logs" :key="log.id" class="border-t"><td class="p-3">{{ new Date(log.createdAt).toLocaleString() }}</td><td>{{ log.actorName }}</td><td>{{ log.action }}</td><td class="capitalize">{{ log.targetType }}: {{ log.targetName }}</td></tr></tbody></table></section><section class="table-shell mt-6"><h2 class="border-b p-4 font-bold">Financial ledger</h2><table class="w-full text-left text-sm"><tbody><tr v-for="entry in ledger" :key="entry.id" class="border-t"><td class="p-3 capitalize">{{ entry.type.replaceAll('_',' ') }}</td><td>{{ formatUzs(entry.amountMinor) }}</td><td>{{ entry.paymentName }}</td><td>{{ entry.memberName }}</td></tr></tbody></table></section></template></main></template>
