<script setup lang="ts">
import { useApiClient } from '~/services/api-client'
import type { DashboardSummary, ReservationsByStatusPoint, SuccessfulPaymentsByDayPoint } from '~/types/dashboard'
definePageMeta({ layout: 'admin' })
const summary = ref<DashboardSummary | null>(null); const statusPoints = ref<ReservationsByStatusPoint[]>([]); const paymentPoints = ref<SuccessfulPaymentsByDayPoint[]>([]); const loading = ref(true); const error = ref<string | null>(null); const success = ref<string | null>(null)
const formatCents = (value: number) => formatUzs(value)
async function refresh(): Promise<void> { loading.value = true; error.value = null; try { const api = useApiClient(); const [summaryData, statuses, payments] = await Promise.all([api.request<DashboardSummary>('/admin/dashboard'), api.request<ReservationsByStatusPoint[]>('/admin/dashboard/reservations-by-status'), api.request<SuccessfulPaymentsByDayPoint[]>('/admin/dashboard/payments-by-day')]); summary.value = summaryData; statusPoints.value = statuses; paymentPoints.value = payments; success.value = 'Dashboard refreshed with the latest server data.' } catch (caught: unknown) { summary.value = null; statusPoints.value = []; paymentPoints.value = []; error.value = caught instanceof Error ? caught.message : 'Dashboard could not be loaded.' } finally { loading.value = false } }
onMounted(refresh)
</script>
<template><main class="mx-auto max-w-6xl px-6 py-10"><header class="flex justify-between gap-4"><div><p class="text-sm font-semibold text-indigo-600">Administrator</p><h1 class="text-3xl font-bold">Operations dashboard</h1></div><button class="rounded-lg border px-4 py-2" :disabled="loading" @click="refresh">Refresh</button></header><p v-if="error" class="mt-5 rounded bg-red-50 p-3 text-red-700" role="alert">{{ error }}</p><p v-if="success" class="mt-5 rounded bg-emerald-50 p-3 text-emerald-700" role="status">{{ success }}</p><div v-if="loading" class="mt-8 grid grid-cols-2 gap-4 lg:grid-cols-4"><div v-for="n in 4" :key="n" class="h-28 animate-pulse rounded bg-slate-100" /></div><p v-else-if="!summary" class="mt-8 rounded border border-dashed p-8 text-center">No dashboard data is available for this date range.</p><template v-else><p class="mt-5 text-sm text-slate-600">Range: {{ new Date(summary.dateRange.from).toLocaleDateString() }} – {{ new Date(summary.dateRange.to).toLocaleDateString() }}. Server cache is invalidated and refetched after reservation mutations.</p><section class="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><article v-for="metric in [{label:'Resources',value:summary.totalResources},{label:'Reservations',value:summary.totalReservations},{label:'Confirmed',value:summary.confirmedReservations},{label:'Revenue',value:formatCents(summary.successfulPaymentAmountMinor)}]" :key="metric.label" class="rounded-xl border p-5"><p class="text-sm text-slate-500">{{ metric.label }}</p><p class="mt-2 text-2xl font-bold">{{ metric.value }}</p></article></section><section class="mt-8 grid gap-6 lg:grid-cols-2"><article class="rounded-xl border p-5"><h2 class="font-bold">Reservations by status</h2><p v-if="!statusPoints.length" class="mt-4 text-sm text-slate-500">No reservations in range.</p><div v-for="point in statusPoints" :key="point.status" class="mt-4"><div class="flex justify-between text-sm"><span>{{ point.status }}</span><strong>{{ point.count }}</strong></div><div class="mt-1 h-2 rounded bg-slate-100"><div class="h-2 rounded bg-indigo-600" :style="{ width: `${Math.min(100, point.count * 10)}%` }" /></div></div></article><article class="rounded-xl border p-5"><h2 class="font-bold">Successful payments by day</h2><p v-if="!paymentPoints.length" class="mt-4 text-sm text-slate-500">No successful payments in range.</p><div v-for="point in paymentPoints" :key="point.date" class="mt-4 flex justify-between text-sm"><span>{{ point.date }}</span><strong>{{ formatCents(point.amountMinor) }}</strong></div></article></section></template></main></template>
